version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "./requirements_test.txt" }}

      - run:
          name: Run Test
          command: tox

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "./requirements_test.txt" }}
          paths:
            - ".tox"

      - run:
          name: Report Coverage to Codacy
          command: |
            if [[ -n "${CODACY_PROJECT_TOKEN}" ]]; then
              apt-get update && apt-get install -y git
              pip3 install codacy-coverage
              python-codacy-coverage -r coverage.xml
            fi
